---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes

  - name: remove apache2 and php package
    apt:
      name: 
        - apache2
        - liapache2-mod-php
      state: absent
      update_cache: yes
